# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [3]:
import numpy as  np

#### 2. Print the numpy version and the configuration 

In [10]:
print(np.__version__)

1.19.5


#### 3. Create a null vector of size 10

In [4]:
vector = np.zeros(10)
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [13]:
print(vector.size)

10


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [ ]:
python -c "import numpy; numpy.info(numpy.add)"

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [7]:
vector2 = np.zeros(10)
vector2[4] = 1
print(vector2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [9]:
vector3 = np.arange(10,50)
print(vector3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last)

In [14]:
vector = np.arange(0,10)
vector2=vector[::-1]
print(vector2)


[9 8 7 6 5 4 3 2 1 0]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [19]:
array = np.arange(0,9).reshape(3,3)
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [24]:
array1 = np.nonzero([1,2,0,0,4,0])
print(array1)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix

In [27]:
matrix = np.eye(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [28]:
matrix = np.random.random((3,3,3))
print(matrix)

[[[0.63092478 0.83884007 0.64444078]
  [0.05603833 0.23592711 0.31388493]
  [0.64247471 0.00236163 0.38435587]]

 [[0.58804801 0.39363    0.33322682]
  [0.57538108 0.24530579 0.15501747]
  [0.54092206 0.53777935 0.30605443]]

 [[0.37498413 0.99752683 0.91926657]
  [0.9567811  0.07536693 0.18023785]
  [0.6791176  0.62831321 0.05989442]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [34]:
matrix = np.random.random((10,10))
##print(matrix)
min_matrix = matrix.min()
max_matrix = matrix.max()
print(min_matrix,max_matrix)

0.011259848182853194 0.9880486865649398


#### 14. Create a random vector of size 30 and find the mean value

In [36]:
vector = np.random.random((10))
mean_vector = vector.mean()
print(mean_vector)

0.38076381596059755


#### 15. Create a 2d array with 1 on the border and 0 inside

In [38]:
array = np.ones((10,10))
array[1:-1,1:-1]=0
print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [46]:
array = np.random.random((3,3))
print(array)
x = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print(x)

[[0.0173317  0.1957581  0.3505143 ]
 [0.73350728 0.2961475  0.41378098]
 [0.82771236 0.55991734 0.41160145]]
[[0.         0.         0.         0.         0.        ]
 [0.         0.0173317  0.1957581  0.3505143  0.        ]
 [0.         0.73350728 0.2961475  0.41378098 0.        ]
 [0.         0.82771236 0.55991734 0.41160145 0.        ]
 [0.         0.         0.         0.         0.        ]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [1]:
##nan
##False
##False
##nan
##True
##False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [4]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [5]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [6]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)
